# Generated by Django 3.2.19 on 2023-06-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tododetails',
            name='priority',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tododetails',
            name='task',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
