version: "3.9"
services:
  mysql:
    image: mysql:8
    container_name: mysqllocal
    restart: unless-stopped
    env_file: .env
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
